using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Linq;


namespace ExampleData
{
    public class ExampleDataFunctions
    {
        public ExampleDataFunctions()
        {

        }
        public string GenerateRandomString(int length)
        {
            StringBuilder rand_str = new StringBuilder();
            Random random = new Random();
            char letter;

            for (int i = 0; i < length; i++)
            {
                double flt = random.NextDouble();
                int shift = Convert.ToInt32(Math.Floor(25 * flt));
                letter = Convert.ToChar(shift + 65);
                rand_str.Append(letter);
            }

            return rand_str.ToString();
        }

        public int GenerateRandomNumber(int lowRange, int highRange)
        {
            Random random = new Random();
            int generatedNum = random.Next(lowRange, highRange);
            return generatedNum;
        }

        public DateTime GenerateRandomDate()
        {
            DateTime start = new DateTime(1995, 06, 01);
            Random gen = new Random();
            int range = (DateTime.Today - start).Days;
            return start.AddDays(gen.Next(range));
        }
        // Total 74 Locations
        public string GenerateRandomSkillCategory(int entry)
        {
            string[] randomListOfSkillCategories = {
                "Mechanical Engineering",
                "Civil Engineering",
                "Chemical Engineering",
                "Biomedical Engineering",
                "Electrical Engineering",
                "Industrial Engineering",
                "Aerospace Engineering",
                "Nuclear Engineering",
                "Agricultural Engineering",
                "Aquacultural Engineering",
                "Geological Engineering",
                "Materials Engineering",
                "Manufacturing Engineering",
                "Mining Engineering",
                "Environmental Engineering",
                "Software Engineering",
                "Statistical Analysis",
                "Quantitative Reports",
                "Quantitative Research",
                "Needs Analysis",
                "Modification",
                "Modeling",
                "Documentation",
                "Database Management",
                "Database Design",
                "Data Mining",
                "Data Analytics",
                "Compiling Statistics",
                "Big Data",
                "Algorithms",
                "Accounting",
                "Project Management",
                "Web Design",
                "Enterprise Systems",
                "Project Planning",
                "Food, Nutrition and Health",
                "Global Resource Systems",
                "Food and Resource Economics",
                "Internation Relations",
                "Accounting",
                "Architecture",
                "Building and Construction",
                "Marketing",
                "Document Writing",
                "Law",
                "Design and Media",
                "Paramedicine",
                "Medicine",
                "Information Technology",
                "Marine Biology",
                "Marine Engineering",
                "Data Engineering",
                "Bridge Construction",
                "Mechanics",
                "Artificial Intelligence"
            };

            List<string> readableSkillCategories = new List<string>(randomListOfSkillCategories);

            return readableSkillCategories[entry];
        }

        public string GenerateRandomSkills(int entry)
        {
            string[] randomListOfSkills = {
                "IDE",
                "Frameworks",
                "Cloud Tools",
                "Data Science",
                "Source Control",
                "Prototyping",
                "DevOps",
                "Notifications",
                "UML",
                "Applications",
                "Certifications",
                "Coding",
                "Computing",
                "Configuration",
                "Customer Support",
                "Debugging",
                "Design",
                "Development",
                "Hardware",
                "HTML",
                "Implementation",
                "Information Technology",
                "ICT (Information and Communications Technology)",
                "Infrastructure",
                "Languages",
                "Maintenance",
                "Network Architecture",
                "Network Security",
                "Networking",
                "New Technologies",
                "Operating Systems",
                "Programming",
                "Restoration",
                "Security",
                "Servers",
                "Software",
                "Solution Delivery",
                "Storage",
                "Structures",
                "Systems Analysis",
                "Technical Support",
                "Technology",
                "Testing",
                "Tools",
                "Training",
                "Troubleshooting",
                "Usability",
                "Benchmarking",
                "Budget Planning",
                "Engineering",
                "Fabrication",
                "Following Specifications",
                "Operations",
                "Performance Review",
                "Project Planning",
                "Quality Assurance",
                "Quality Control",
                "Scheduling",
                "Task Delegation",
                "Task Management",
                "Content Management Systems (CMS)",
                "Blogging",
                "Digital Photography",
                "Digital Media",
                "Networking",
                "Search Engine Optimization (SEO)",
                "Social Media Platforms (Twitter, Facebook, Instagram, LinkedIn, TikTok, Medium, etc.)",
                "Web Analytics",
                "Automated Marketing Software",
                "Client Relations",
                "Email",
                "Requirements Gathering",
                "Research",
                "Subject Matter Experts (SMEs)",
                "Technical Documentation",
                "Information Security",
                "Microsoft Office Certifications",
                "Video Creation",
                "Customer Relationship Management (CRM)",
                "Productivity Software",
                "Cloud/SaaS Services",
                "Database Management",
                "Telecommunications",
                "Human Resources Software",
                "Accounting Software",
                "Enterprise Resource Planning (ERP) Software",
                "Database Software",
                "Query Software",
                "Blueprint Design",
                "Medical Billing",
                "Medical Coding",
                "Sonography",
                "Structural Analysis",
                "Artificial Intelligence (AI)",
                "Mechanical Maintenance",
                "Manufacturing",
                "Inventory Management",
                "Numeracy",
                "Information Management",
                "Hardware Verification Tools and Techniques",
                "Hardware Description Language (HDL)",
                "Git",
                "GitLab",
                "GitHub",
                "Bitbucket",
                "Ansible",
                "Jenkins",
                "Chef",
                "Puppet",
                "Kubernetes",
                "Docker",
                "Slack",
                "Microsoft Teams",
                "Zoom",
                "GoToMeeting",
                "Skype",
                "AWS",
                "Azure",
                "GCP",
                "Raygun",
                "SignalFx",
                "Splunk Cloud",
                "AppDynamics",
                "Catchpoint",
                "VictorOps",
                "Selenium",
                "Cypress",
                "Gremlin",
                "ServiceNow",
                "Statuspage",
                "4th Dimension/4D",
                "ABAP",
                "ABC",
                "ActionScript",
                "Ada",
                "Agilent VEE",
                "Algol",
                "Alice",
                "Angelscript",
                "Apex",
                "APL",
                "AppleScript",
                "Arc",
                "Arduino",
                "ASP",
                "AspectJ",
                "Assembly",
                "ATLAS",
                "Augeas",
                "AutoHotkey",
                "AutoIt",
                "AutoLISP",
                "Automator",
                "Avenue",
                "Awk",
                "Bash",
                "(Visual) Basic",
                "bc",
                "BCPL",
                "BETA",
                "BlitzMax",
                "Boo",
                "Bourne Shell",
                "Bro",
                "C",
                "C Shell",
                "C#",
                "C++",
                "C++/CLI",
                "C-Omega",
                "Caml",
                "Ceylon",
                "CFML",
                "cg",
                "Ch",
                "CHILL",
                "CIL",
                "CL (OS/400)",
                "Clarion",
                "Clean",
                "Clipper",
                "Clojure",
                "CLU",
                "COBOL",
                "Cobra",
                "CoffeeScript",
                "ColdFusion",
                "COMAL",
                "Common Lisp",
                "Coq",
                "cT",
                "Curl",
                "D",
                "Dart",
                "DCL",
                "DCPU-16 ASM",
                "Delphi/Object Pascal",
                "DiBOL",
                "Dylan",
                "E",
                "eC",
                "Ecl",
                "ECMAScript",
                "EGL",
                "Eiffel",
                "Elixir",
                "Emacs Lisp",
                "Erlang",
                "Etoys",
                "Euphoria",
                "EXEC",
                "F#",
                "Factor",
                "Falcon",
                "Fancy",
                "Fantom",
                "Felix",
                "Forth",
                "Fortran",
                "Fortress",
                "(Visual) FoxPro",
                "Gambas",
                "GNU Octave",
                "Go",
                "Google AppsScript",
                "Gosu",
                "Groovy",
                "Haskell",
                "haXe",
                "Heron",
                "HPL",
                "HyperTalk",
                "Icon",
                "IDL",
                "Inform",
                "Informix-4GL",
                "INTERCAL",
                "Io",
                "Ioke",
                "J",
                "J#",
                "JADE",
                "Java",
                "Java FX Script",
                "JavaScript",
                "JScript",
                "JScript.NET",
                "Julia",
                "Korn Shell",
                "Kotlin",
                "LabVIEW",
                "Ladder Logic",
                "Lasso",
                "Limbo",
                "Lingo",
                "Lisp",
                "Logo",
                "Logtalk",
                "LotusScript",
                "LPC",
                "Lua",
                "Lustre",
                "M4",
                "MAD",
                "Magic",
                "Magik",
                "Malbolge",
                "MANTIS",
                "Maple"
            };

            List<string> readableSkills = new List<string>(randomListOfSkills);

            return readableSkills[entry];
        }

        // Total 74 Locations
        public string GenerateReadableLocations(int entry)
        {
            string[] randomListOfLocations = {
                "Laval ",
"Trail ",
"Moose Jaw ",
"Corner Brook ",
"Guelph ",
"Thunder Bay ",
"Oakville ",
"Dorval ",
"Granby ",
"La Salle ",
"Powell River ",
"Woodstock ",
"Winnipeg ",
"Brandon ",
"Hamilton ",
"Belleville ",
"Quesnel ",
"Lethbridge ",
"Waterloo ",
"Summerside ",
"Ferryland ",
"Placentia ",
"Kingston ",
"Louisbourg ",
"Midland ",
"Saint-Eustache ",
"Havre-Saint-Pierre ",
"Chilliwack ",
"Sydney ",
"Gatineau ",
"Yarmouth ",
"Happy Valley ",
"Hong Kong",
"Cranbrook ",
"Moose Factory ",
"Campbell River ",
"Cavendish ",
"White Rock ",
"West Nipissing ",
"Asbestos ",
"Hay River ",
"Nelson ",
"Vernon ",
"Val-d ",
"Fort Smith ",
"Fort McMurray ",
"Trois-Rivi ",
"Lunenburg ",
"Dawson Creek ",
"Estevan ",
"Elliot Lake ",
"Fort Saint James ",
"Souris ",
"Stratford ",
"Fredericton ",
"Inuvik ",
"Whitehorse ",
"Saint Boniface ",
"Temiskaming Shores ",
"Fort Frances ",
"Sorel-Tracy ",
"Peterborough ",
"Kuujjuaq ",
"Calgary ",
"Rimouski ",
"Prince George ",
"Delta ",
"Lake Louise ",
"Redmond ",
"Sweetwater ",
"Morristown ",
"Effingham ",
"Weston ",
"Hays " };

            List<string> readableLocations = new List<string>(randomListOfLocations);

            return readableLocations[entry];
        }
        // TOTAL 74 COMPANIES
        public string GenerateReadableCompanies(int entry)
        {
            string[] randomListOfCompanies = {
                "E.W. Scripps Company",
"Earthlink, Inc.",
"Eastman Chemical Company",
"Eastman Kodak Company",
"Eaton Corporation",
"Echostar Communications Corporation",
"Ecolab Inc.",
"Edison International",
"EGL Inc.",
"El Paso Corporation",
"Electronic Arts Inc.",
"Electronic Data Systems Corp.",
"Eli Lilly and Company",
"EMC Corporation",
"Emcor Group Inc.",
"Emerson Electric Co.",
"Encompass Services Corporation",
"Energizer Holdings Inc.",
"Energy East Corporation",
"Engelhard Corporation",
"Enron Corp.",
"Entergy Corporation",
"Enterprise Products Partners L.P.",
"EOG Resources, Inc.",
"Equifax Inc.",
"Equitable Resources Inc.",
"Equity Office Properties Trust",
"Equity Residential Properties Trust",
"Estee Lauder Companies Inc.",
"Exelon Corporation",
"Exide Technologies",
"Expeditors International of Washington Inc.",
"Express Scripts Inc.",
"ExxonMobil Corporation",
"Fairchild Semiconductor International Inc.",
"Family Dollar Stores Inc.",
"Farmland Industries Inc.",
"Federal Mogul Corp.",
"Federated Department Stores Inc.",
"Federal Express Corp.",
"Felcor Lodging Trust Inc.",
"Ferro Corp.",
"Fidelity National Financial Inc.",
"Fifth Third Bancorp",
"First American Financial Corp.",
"First Data Corp.",
"First National of Nebraska Inc.",
"First Tennessee National Corp.",
"FirstEnergy Corp.",
"Fiserv Inc.",
"Fisher Scientific International Inc.",
"FleetBoston Financial Co.",
"Fleetwood Enterprises Inc.",
"Fleming Companies Inc.",
"Flowers Foods Inc.",
"Flowserv Corp",
"Fluor Corp",
"FMC Corp",
"Foamex International Inc",
"Foot Locker Inc",
"Footstar Inc.",
"Ford Motor Co",
"Forest Laboratories Inc.",
"Fortune Brands Inc.",
"Foster Wheeler Ltd.",
"FPL Group Inc.",
"Franklin Resources Inc.",
"Freeport McMoran Copper & Gold Inc.",
"Frontier Oil Corp",
"Furniture Brands International Inc.",
"Gannett Co., Inc.",
"Gap Inc.",
"Gateway Inc.",
"GATX Corporation",
            };

            List<string> readableCompanies = new List<string>(randomListOfCompanies);
            return readableCompanies[entry];

        }

        // Total 191 offices
        public string GenerateReadableOffices(int entry)
        {
            string[] randomListofOffices = {
                "Phoenix ",
"New Hope ",
"Kaneohe ",
"Ecorse ",
"Monmouth ",
"Beverly ",
"Port Gibson ",
"Madison ",
"Montclair ",
"Shelby ",
"Silver Spring ",
"Woonsocket ",
"Nanticoke ",
"Saint Johnsbury ",
"Asheville ",
"Barrington ",
"Castine ",
"Grinnell ",
"Waterbury ",
"Blackfoot ",
"Lewiston ",
"Kenosha ",
"Sanford ",
"Cranford ",
"Gloversville ",
"Honolulu ",
"South Kingstown ",
"Hattiesburg ",
"Hollywood ",
"Dothan ",
"Exeter ",
"Alhambra ",
"Sierra Vista ",
"North Haven ",
"Lombard ",
"Greensburg ",
"Fort Payne ",
"Asbury Park ",
"Park Forest ",
"Bainbridge ",
"Tallahassee ",
"Santa Monica ",
"Watertown ",
"Frederick ",
"Hartsville ",
"Yonkers ",
"El Reno ",
"Bisbee ",
"Thibodaux ",
"South Bend ",
"Truth or Consequences ",
"Hanover ",
"Taos ",
"Roselle ",
"Laredo ",
"Hugo ",
"San Rafael ",
"Wilmington ",
"Garland ",
"Manchester ",
"Huron ",
"Des Plaines ",
"Perth Amboy ",
"Youngstown ",
"Ten Sleep ",
"Canyon ",
"Ontario ",
"Shreveport ",
"Alamosa ",
"East Hartford ",
"Macomb ",
"Braintree ",
"Odessa ",
"Vernal ",
"Prichard ",
"Grayling ",
"Murray ",
"Richmond ",
"Muscatine ",
"Monroeville ",
"Santa Clarita ",
"Rockford ",
"Tombstone ",
"New Orleans ",
"Hobart ",
"Florissant ",
"Elwood ",
"Barre ",
"Okmulgee ",
"Lorain ",
"Brattleboro ",
"Flushing ",
"Winslow ",
"New Paltz ",
"Hobbs ",
"Carlisle ",
"Powell ",
"Victoria ",
"Long Beach ",
"Kanab ",
"Smithton ",
"Murray Bridge ",
"Healesville ",
"Mount Isa ",
"Wynyard ",
"Ingham ",
"Temora ",
"Sydney ",
"Tumut ",
"Nambucca Heads ",
"Gunnedah ",
"Horsham ",
"Charters Towers ",
"Dubbo ",
"Tamworth ",
"Maitland ",
"Katherine ",
"Hamilton ",
"Armidale ",
"Bowral ",
"Mount Morgan ",
"Adelaide ",
"Canberra ",
"Raymond Terrace ",
"Goondiwindi ",
"Dampier ",
"Broome ",
"Castlemaine ",
"Narrogin ",
"Kurri Kurri ",
"Moree ",
"Darwin ",
"Bega ",
"West Wyalong ",
"Port Hedland ",
"Muswellbrook ",
"Kerang ",
"Wonthaggi ",
"Whyalla ",
"Charleville ",
"Beaconsfield ",
"Forster ",
"Gundagai ",
"Goolwa ",
"Cairns ",
"Wagga Wagga ",
"Shepparton ",
"Warragul ",
"Glen Innes ",
"Taree ",
"Ballina ",
"Northam ",
"Queanbeyan ",
"Colac ",
"Kalgoorlie ",
"Cooma ",
"Nowra-Bomaderry ",
"Moranbah ",
"Loxton ",
"Kingston ",
"Launceston ",
"Ulladulla ",
"Goulburn ",
"Bowen ",
"Wyong ",
"Moe ",
"Traralgon ",
"Lakes Entrance ",
"Mount Gambier ",
"Ceduna ",
"Rosebery ",
"Cootamundra ",
"Maryborough ",
"Devonport ",
"Tom Price ",
"Port Augusta ",
"Narrabri ",
"Ulverstone ",
"Echuca ",
"Bunbury ",
"Orange ",
"Stanley ",
"Newcastle ",
"Tennant Creek ",
"Cobar ",
"Weipa ",
"Cowra ",
"Balranald ",
"Port Adelaide Enfield ",
"Camden ",
"Wellington ",

            };
            List<string> readableOffices = new List<string>(randomListofOffices);
            return readableOffices[entry];
        }

        //Total 10 phones
        public string GeneratePhone(int entry)
        {
            string[] phones = {
                "200-456-7890",
"293-789-1234",
"376-052-0000",
"453-789-2314",
"528-789-3444",
"328-123-5231",
"390-567-2347",
"987-154-1678",
"811-634-7342",
"731-333-6622"};
            List<string> phoneList = new List<string>(phones);
            return phoneList[entry];
        }

        public string GenerateType(int entry)
        {
            string[] types = { "employee", "contractor" };
            List<string> typeList = new List<string>(types);
            return typeList[entry];
        }

        //Total 150 groups
        public string GenerateReadableGroups(int entry)
        {
            string[] randomListOfSectors = {
                "International Affairs",
"Beer, Wine, and Liquor Stores",
"Other Personal and Household Goods Repair and Maintenance",
"Hair, Nail, and Skin Care Services",
"Management Consulting Services",
"Synthetic Dye and Pigment Manufacturing",
"Electric Lamp Bulb and Part Manufacturing",
"Cement Manufacturing",
"Soap and Cleaning Compound Manufacturing",
"Other Concrete Product Manufacturing",
"Cosmetics, Beauty Supplies, and Perfume Stores",
"Office Furniture (including Fixtures) Manufacturing",
"Sound Recording Studios",
"Paper Bag and Coated and Treated Paper Manufacturing",
"Broilers and Other Meat Type Chicken Production",
"Fish and Seafood",
"Electronic and Precision Equipment Repair and Maintenance",
"Other Electronic Parts and Equipment Merchant Wholesalers",
"Other General Government Support",
"Commercial Banking",
"Elementary and Secondary Schools",
"Stationery Product Manufacturing",
"Lessors of Other Real Estate Property",
"Flooring Contractors",
"Metal Can, Box, and Other Metal Container",
"Children's and Infants' Clothing Stores",
"All General Purpose Machinery Manufacturing",
"Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)",
"Optical Goods Stores",
"Computer and Peripheral Equipment Manufacturing",
"Inland Water Transportation",
"Leather and Hide Tanning and Finishing",
"Limo Service",
"Civic and Social Organizations",
"Horses Production",
"Cut and Sew Apparel Contractors",
"Other Activities Related to Credit Intermediation",
"Savings Institutions",
"Sewing, Needlework, and Piece Goods Stores",
"Offices of Physicians",
"Credit Card Issuing",
"Ferrous Metal Foundries",
"Wiring Device Manufacturing",
"Wood Kitchen Cabinet and Countertop Manufacturing",
"Book Publishers",
"All Other Specialty Trade Contractors",
"Vegetable and Melon Farming",
"Knit Fabric Mills",
"Piece Goods, Notions, and Other Dry Goods Merchant Wholesalers",
"Other Grocery and Related Products Merchant Wholesalers",
"Forest Nurseries and Gathering of Forest Products",
"Heavy Duty Truck Manufacturing",
"Political Organizations",
"Plumbing and Heating Equipment and Supplies (Hydronics) Merchant Wholesalers",
"Administration of Urban Planning and Community and Rural Development",
"Lime Manufacturing",
"Plate Work and Fabricated Structural Product Manufacturing",
"Industrial Machinery and Equipment Merchant Wholesalers",
"Other Depository Credit Intermediation",
"Other Transit and Ground Passenger Transportation",
"Goat Farming",
"Port Operations",
"News Syndicates",
"General Line Grocery Merchant Wholesalers",
"All Fabricated Metal Product Manufacturing",
"Record Production",
"Scenic and Sightseeing Transportation, Land",
"Farm Product Warehousing and Storage",
"Photographic Equipment and Supplies Merchant Wholesalers",
"Interurban and Rural Bus Transportation",
"Residential Building Construction",
"Doll, Toy, and Game Manufacturing",
"Dairy and Milk Production",
"Office Machinery and Equipment Rental and Leasing",
"Technical and Trade Schools",
"Industrial Gas Manufacturing",
"Regulation, Licensing, and Inspection of Miscellaneous Commercial Sectors",
"Fine Arts Schools",
"Metalworking Machinery Manufacturing",
"Metal Service Centers and Other Metal Merchant Wholesalers",
"Other Insurance Funds",
"Other Traveler Accommodation",
"Navigational, Measuring, Electromedical, and Control Instruments Manufacturing",
"Research and Development in the Physical, Engineering, and Life Sciences",
"Wood Container and Pallet Manufacturing",
"Administration of Veterans' Affairs",
"Flower, Nursery Stock, and Florists' Supplies Merchant Wholesalers",
"Lessors of Residential Buildings and Dwellings",
"Casino Hotels",
"Petroleum and Petroleum Products Merchant Wholesalers (except Bulk Stations and Terminals)",
"Home Health Care Services",
"Home Furnishing Merchant Wholesalers",
"All Other Professional, Scientific, and Technical Services",
"Seasoning and Dressing Manufacturing",
"Sewage Treatment Facilities",
"Other Telecommunications",
"Other Chemical and Allied Products Merchant Wholesalers",
"Architectural Services",
"Distilleries",
"Turkey Production",
"Zoos and Botanical Gardens",
"Health and Welfare Funds",
"Other Heavy and Civil Engineering Construction",
"Data Processing, Hosting, and Related Services",
"Footwear Merchant Wholesalers",
"Wholesale Trade Agents and Brokers",
"Poultry and Poultry Product Merchant Wholesalers",
"Laminated Plastics Plate, Sheet (except Packaging), and Shape Manufacturing",
"Limousine Service",
"Fish and Seafood Merchant Wholesalers",
"Breweries",
"Urethane and Other Foam Product (except Polystyrene) Manufacturing",
"Automobile and Other Motor Vehicle Merchant Wholesalers",
"Gypsum Product Manufacturing",
"Open-End Investment Funds",
"Tobacco Product Manufacturing",
"Airport Operations",
"Convention and Trade Show Organizers",
"Pet Care (except Veterinary) Services",
"Fish and Seafood Markets",
"Used Merchandise Stores",
"Language Schools",
"Metal Can, Box, and Other Metal Container (Light Gauge) Manufacturing",
"Dairy Cattle and Milk Production",
"Scheduled Air Transportation",
"Noncitrus Fruit and Tree Nut Farming",
"Rice Farming",
"Ice Cream and Frozen Dessert Manufacturing",
"Offices of Chiropractors",
"Audio and Video Equipment Manufacturing",
"Tour Operators",
"All Other General Purpose Machinery Manufacturing",
"All Other Animal Production",
"Horses and Other Equine Production",
"Charter Bus Industry",
"Fruit and Vegetable Markets",
"Local Messengers and Local Delivery",
"Commodity Contracts Brokerage",
"Paint, Varnish, and Supplies Merchant Wholesalers",
"Meat Markets",
"Motor Vehicle Brake System Manufacturing",
"Orange Groves",
"Gasoline Stations with Convenience Stores",
"Regulation of Agricultural Marketing and Commodities",
"Material Handling Equipment Manufacturing",
"All Other Fabricated Metal Product Manufacturing",
"Fabric Coating Mills",
"Port and Harbor Operations",
"Other Electronic Parts Wholesalers",
"Community Food Services",
            };

            List<string> readableSectors = new List<string>(randomListOfSectors);
            return readableSectors[entry];
        }
        // Total 200 names
        public string GenerateWorkerNames(int entry)
        {
            string[] randomNames = {
                "Samson",
"Kris",
"Lily-Mae",
"Petra",
"Amelie",
"Trixie",
"Russell",
"Lily-Mai",
"Isobella",
"Eoin",
"Pooja",
"Owain",
"Amman",
"Aleena",
"Brooke",
"Ashwin",
"Aj",
"Wasim",
"Kirsty",
"Lowri",
"Francesco",
"Evie-May",
"Ayoub",
"Mehmet",
"Patricia",
"Diogo",
"Taryn",
"Jimmy",
"Danish",
"Murat",
"Mariana",
"Nadia",
"Melody",
"Dominika",
"Lizzie",
"Tamzin",
"Hania",
"Abul",
"Nabil",
"Patrik",
"Tiah",
"Khloe",
"Justine",
"Menna",
"Kamile",
"Safwan",
"Louisa",
"Viktor",
"Clarice",
"Tasnia",
"Zaki",
"Stephanie",
"Jana",
"Neal",
"Sheila",
"Ellesse",
"Jayson",
"Viola",
"Julian",
"Samara",
"Ryan",
"Alysha",
"Beyonce",
"Zander",
"Amit",
"Gina",
"Sanjeev",
"Nadir",
"Cameron",
"Benas",
"Kennedy",
"Manuel",
"Patience",
"Tonisha",
"Delia",
"Dominic",
"Klara",
"Cali",
"Bianca",
"Evie-Mai",
"Fergus",
"Roisin",
"Kaja",
"Cristina",
"Lexi",
"Mercedes",
"Nicolle",
"Bayley",
"Steffan",
"Yasin",
"Levison",
"Masuma",
"Ellouise",
"Georgie",
"Sallie",
"Zavier",
"Hibba",
"Mike",
"Mikey",
"Aran",
"Tomlinson",
"Mccartney",
"Forbes",
"Naylor",
"Sosa",
"Legge",
"Butler",
"Vu",
"Peck",
"Watts",
"Moore",
"Shaw",
"Fowler",
"Burnett",
"Copeland",
"Macias",
"Hensley",
"Xiong",
"Hawes",
"Croft",
"Amin",
"Herbert",
"Burns",
"Rasmussen",
"Graham",
"Webb",
"Mcpherson",
"Worthington",
"Acosta",
"Harding",
"Werner",
"Ryder",
"Gilmour",
"Ramsey",
"Jacobs",
"Black",
"Ahmad",
"Barton",
"Zavala",
"Day",
"Todd",
"Roth",
"Fritz",
"Lawson",
"Tierney",
"Trejo",
"Rodrigues",
"Riley",
"Mayer",
"Reed",
"Stout",
"Goodwin",
"Pearce",
"Kearney",
"Gould",
"Akhtar",
"Hayden",
"Hoover",
"Stott",
"Ali",
"Murray",
"Rawlings",
"Shah",
"Irwin",
"Cantrell",
"Mcnally",
"Perez",
"Bowers",
"Salazar",
"Oliver",
"Davison",
"Denton",
"Mcfadden",
"Hook",
"Navarro",
"Reid",
"Schultz",
"Santana",
"Irving",
"Battle",
"Needham",
"Franklin",
"Norman",
"Hogg",
"Cameron",
"Contreras",
"Bird",
"Stone",
"Vazquez",
"Kramer",
"Roberts",
"Cook",
"Coles",
"Preece",
"Huff",
"Dupont",
"Dixon",
"Barr",
"Davidson",
"Steele",
            };
            List<string> readableNames = new List<string>(randomNames);
            return readableNames[entry];
        }

        public string GenerateReadableTitles(int entry)
        {
            string[] randomTitles = {
                "Atmospheric Chemist",
"Swaging Machine Operator",
"Biochemistry Technologist",
"Tissue Technologist",
"Halal Butcher",
"Automotive Electrician",
"China Decorator",
"Thermodynamicist",
"Dental Secretary",
"Shellfish Dredge Operator",
"Certified Ski Patroller",
"Bacteriology Technician",
"Psychiatric Technician",
"Vocational Rehabilitation Counselor",
"Radio Time Sales Supervisor",
"Hospice Social Worker",
"Library Clerk",
"Port Crane Operator",
"Grounds Caretaker",
"AIDS Social Worker",
"Youth Pastor",
"Activities Assistant",
"Payroll Examiner",
"Bookbinder",
"Juke Box Mechanic",
"Television Audio Engineer",
"Life Science Taxonomist",
"Fire Control Technician B (Ballistic Missile Fire Control)",
"An/Bsy-1 (Xn-1)(V) Basic Organizational Maintenance Technician",
"Feed Manager",
"Boring Mill Operator for Metal",
"Ventriloquist",
"Environmental Statistician",
"Highway Engineer",
"Ethnoarchaeology Professor",
"Aquatic Biologist",
"Hatchery Worker",
"Marine Air Ground Task Force (Magtf) Planners",
"Soloist",
"Metal Engraver",
"Citizenship Teacher",
"Fur Trimmer",
"Facilities Engineer",
"Garage Door Technician",
"Agricultural Production Engineer",
"Roofer Helper",
"Field Map Technician",
"Tax Compliance Officer",
"Soil Engineer",
"Skip Tracer",
"Home Stereo Equipment Installer",
"Library Cataloging Technician",
"State Highway Police Officer",
"Air Tour Pilot",
"Motor Vehicle Emissions Inspector",
"Cane Cutter",
"Orchard Manager",
"Ballet Soloist",
"Iap Displays Analyst",
"Animal Husbandry Manager",
"Sheep Shearer",
"Mission Commander",
"Ice Cream Server",
"Appellate Conferee",
"Tire Technician",
"Family Practitioner",
"Cement Truck Driver",
"Piano Performance and Pedagogy Professor",
"Arch Cushion Press Operator",
"Tractor Operator",
"Residence Life Coordinator",
"Computer Help Desk Representative",
"Automobile Detailer",
"Packing Line Operator",
"Baseball Scout",
"Nursery School Teacher",
"Nuclear & Chemical Weapons Employment Officer",
"Toy Designer",
"Pet Supplies Salesperson",
"Staff Submarine Warfare Officer",
"Economist",
"Hat Blocking Machine Operator",
"High School French Teacher",
"Cardiopulmonary Technologist",
"Field Map Technician",
"Kiln Door Builder",
"IT Professor",
"Cullet Crusher and Washer",
"Swimmer",
"Tinsmith",
"Tariff Compiling Clerk",
"Lithograph Press Operator",
"Pre-Kindergarten Special Education Teacher",
"Title Investigator",
"Photojournalist",
"Position Classification Specialist",
"Tile Mason",
"Tissue Technologist",
"Municipal Clerk",
"Crown and Bridge Dental Lab Technician",
            };
            List<string> readableTitles = new List<string>(randomTitles);
            return readableTitles[entry];
        }

        // For SkillCategory + Skills. Total of 299 words
        public string GenerateReadableString(int entry)
        {
            string[] randomListOfString = {"HEAD", "CURIOSITIES",
                                                    " HOTLY",
                                                    " DISCIPLINE",
                                                    " HONEYDEW",
                                                    " DIAGONAL",
                                                    " BOARDINGHOUSE",
                                                    " ORTHODOX",
                                                    " GREATEST",
                                                    " AFFLICTION",
                                                    " HEAVY",
                                                    " BOUTIQUE",
                                                    " CHILDREN",
                                                    " BEAD",
                                                    " BABY",
                                                    " AFTERTASTE",
                                                    " PALE",
                                                    " FRIGHTENING",
                                                    " CURATOR",
                                                    " AXIOM",
                                                    " STIFF",
                                                    " PATTERN",
                                                    " HINGE",
                                                    " CRATER",
                                                    " ACROBAT",
                                                    " GLOOMY",
                                                    " EASIER",
                                                    " KITTEN",
                                                    " IDENTITY",
                                                    " COSTUME",
                                                    " BRILLIANT",
                                                    " LAND",
                                                    " CHARISMATIC",
                                                    " HERALD",
                                                    " RIOT",
                                                    " PITCH",
                                                    " EVOKE",
                                                    " ARSON",
                                                    " FORGIVEN",
                                                    " VIBRATION",
                                                    " DISMISSAL",
                                                    " DAREDEVIL",
                                                    " GLIMMER",
                                                    " LORD",
                                                    " UNSURE",
                                                    " HUNT",
                                                    " BANDSAW",
                                                    " CREATURE",
                                                    " DENSE",
                                                    " BONE",
                                                    " RUBY",
                                                    " PEST",
                                                    " ABSURDITIES",
                                                    " ARSON",
                                                    " IRON",
                                                    " WILLOW",
                                                    " ADORABLE",
                                                    " DIVINE",
                                                    " EXCHANGE",
                                                    " KING",
                                                    " HAND",
                                                    " RUBBER",
                                                    " DEMON",
                                                    " INSECURE",
                                                    " IMPOSTER",
                                                    " TASTE",
                                                    " DREAM",
                                                    " PARACHUTE",
                                                    " ANGEL",
                                                    " BEHOLD",
                                                    " BOUNCY",
                                                    " PROPHET",
                                                    " GRASP",
                                                    " FAVORABLE",
                                                    " DISFIGURED",
                                                    " HEATER",
                                                    " LOLLIPOP",
                                                    " CONVERTIBLE",
                                                    " GONE",
                                                    " COSTUMED",
                                                    " HERALD",
                                                    " PLAYTIME",
                                                    " DESPERATE",
                                                    " NEON",
                                                    " DIAMETRIC",
                                                    " HEADLOCK",
                                                    " AGE",
                                                    " AMERICANA",
                                                    " GLUMLY",
                                                    " HOST",
                                                    " ZOMBIE",
                                                    " GREY",
                                                    " FORTRESS",
                                                    " BEAST",
                                                    " HEADACHE",
                                                    " STEALTHY",
                                                    " APOCALYPSE",
                                                    " HEAT",
                                                    " TWELVE",
                                                    " AUTONOMOUS",
                                                    " CULTURAL",
                                                    " AMBIGUOUS",
                                                    " ELECTRON",
                                                    " FESTIVAL",
                                                    " BECAUSE",
                                                    " PESKY",
                                                    " AMBULATORY",
                                                    " PINK",
                                                    " STAR",
                                                    " PROVIDER",
                                                    " BINDING",
                                                    " DIAMOND",
                                                    " DIARY",
                                                    " TRAGIC",
                                                    " FACTION",
                                                    " CREEPY",
                                                    " DISCONNECT",
                                                    " CHUNK",
                                                    " COMPUTER",
                                                    " IMPOSTER",
                                                    " CONCEPT",
                                                    " DISTRIBUTION",
                                                    " ACADEMIC",
                                                    " DONATION",
                                                    " VULTURE",
                                                    " MOMENT",
                                                    " HEARSE",
                                                    " BRUSH",
                                                    " EXTREMIST",
                                                    " AMORAL",
                                                    " CRUTCH",
                                                    " JOYSTICK",
                                                    " SEWAGE",
                                                    " FINGER",
                                                    " LADY",
                                                    " QUEEN",
                                                    " HONEYMOON",
                                                    " FERMENTATION",
                                                    " BEEFCAKE",
                                                    " DOWNTOWN",
                                                    " ULTIMATE",
                                                    " ZERO",
                                                    " MISTAKEN",
                                                    " HANDLEBARS",
                                                    " GRADE",
                                                    " HOPE",
                                                    " CONSPIRACY",
                                                    " CRASHER",
                                                    " CRUCIFIXION",
                                                    " BRANCH",
                                                    " ANYTIME",
                                                    " SCHEMER",
                                                    " IVORY",
                                                    " CHAOTIC",
                                                    " DOOM",
                                                    " HOUND",
                                                    " INJUSTICE",
                                                    " COMPELLING",
                                                    " TENSE",
                                                    " ETERNAL",
                                                    " INJURY",
                                                    " EXPANSION",
                                                    " VIPER",
                                                    " FILAMENT",
                                                    " ALLOWABLE",
                                                    " FORM",
                                                    " SUBWAY",
                                                    " RETREAT",
                                                    " FLAMBOYANT",
                                                    " AUXILIARY",
                                                    " FREEZE",
                                                    " DIAMETRIC",
                                                    " LUXURY",
                                                    " GOGGLES",
                                                    " CALENDAR",
                                                    " BLURB",
                                                    " NEUROTIC",
                                                    " MIXER",
                                                    " VULTURE",
                                                    " ABSURDITIES",
                                                    " BEAK",
                                                    " DOWNRIVER",
                                                    " HEADQUARTERS",
                                                    " STAGE",
                                                    " LIBERATION",
                                                    " SPIKE",
                                                    " SPRITES",
                                                    " ALARM",
                                                    " PARASITE",
                                                    " HUNCHBACK",
                                                    " ESSENCE",
                                                    " GROSS",
                                                    " CHOKE",
                                                    " COGNITIVE",
                                                    " DESPISABLE",
                                                    " ROTTEN",
                                                    " GRINDING",
                                                    " METALLIC",
                                                    " KITTEN",
                                                    " KICK",
                                                    " LEVITATING",
                                                    " HISTORIC",
                                                    " EXTRAVAGANT",
                                                    " FAITHLESS",
                                                    " DRAG",
                                                    " DETAILS",
                                                    " CRUTCH",
                                                    " BOUTIQUE",
                                                    " WARM",
                                                    " ADEQUATE",
                                                    " HELLFIRE",
                                                    " HEAT",
                                                    " COMET",
                                                    " CELEBRITY",
                                                    " UNDERSEA",
                                                    " PRIVATE",
                                                    " ASSOCIATE",
                                                    " BIT",
                                                    " DOMINANT",
                                                    " BELL",
                                                    " THINK",
                                                    " LARGE",
                                                    " EYETOOTH",
                                                    " FRONTIER",
                                                    " COMBAT",
                                                    " FLAVOR",
                                                    " SMART",
                                                    " HAUNTING",
                                                    " CALL",
                                                    " PLASMA",
                                                    " VIXEN",
                                                    " AGE",
                                                    " PRIVILEGE",
                                                    " FIERY",
                                                    " TREED",
                                                    " CRIMSON",
                                                    " SWINDLER",
                                                    " FAITHLESS",
                                                    " PIECES",
                                                    " INNOCENT",
                                                    " FEELINGS",
                                                    " EQUAL",
                                                    " ATTRIBUTE",
                                                    " SKY",
                                                    " HACK",
                                                    " ALCOHOLIC",
                                                    " WOLF",
                                                    " CHOKING",
                                                    " STALLION",
                                                    " ENEMY",
                                                    " WIFE",
                                                    " AIM",
                                                    " FRUSTRATION",
                                                    " GROANER",
                                                    " AIR",
                                                    " DRESS",
                                                    " EPHEMERAL",
                                                    " GETAWAY",
                                                    " JOYRIDE",
                                                    " GRANULARITY",
                                                    " LIBERAL",
                                                    " POET",
                                                    " RIB",
                                                    " TERROR",
                                                    " ABSENCE",
                                                    " BULLET",
                                                    " BEST",
                                                    " HEAT",
                                                    " DEER",
                                                    " NASTY",
                                                    " FUMBLING",
                                                    " ELEVATOR",
                                                    " MARY",
                                                    " BAYONET",
                                                    " PREFAB",
                                                    " WHALE",
                                                    " FATHEAD",
                                                    " HORRIFIC",
                                                    " HEARTS",
                                                    " GOLDFISH",
                                                    " FACE",
                                                    " BRICK",
                                                    " DIGNITARY",
                                                    " EVERLASTING",
                                                    " DIRECTION",
                                                    " CONTINUOUS",
                                                    " GEMS",
                                                    " RASTLED",
                                                    " DISTILERY",
                                                    " PERIODIC",
                                                    " GLOW",
                                                    " INSECT",
                                                    " CRASH",
                                                    " NORM",
                                                    " HOLIDAY",
                                                    " VIPER",
                                                    " EMPATHIC",
                                                    " OFFICER",
                                                    " MOHAWK"};
            List<string> readableString = new List<string>(randomListOfString);

            return readableString[entry];

        }


    }
}