INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'1', N'Mechanical Engineering', N'A');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'10', N'Civil Engineering', N'H');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'11', N'Chemical Engineering', N'X');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'12', N'Biomedical Engineering', N'H');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'13', N'Electrical Engineering', N'I');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'14', N'Industrial Engineering', N'C');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'15', N'Aerospace Engineering', N'T');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'16', N'Nuclear Engineering', N'N');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'17', N'Agricultural Engineering', N'S');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'18', N'Aquacultural Engineering', N'R');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'19', N'Geological Engineering', N'C');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'2', N'Materials Engineering', N'A');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'20', N'Manufacturing Engineering', N'R');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'21', N'Mining Engineering', N'C');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'22', N'Environmental Engineering', N'B');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'23', N'Software Engineering', N'N');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'24', N'Statistical Analysis', N'R');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'25', N'Quantitative Reports', N'J');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'26', N'Quantitative Research', N'M');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'27', N'Needs Analysis', N'X');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'28', N'Modification', N'V');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'29', N'Modeling', N'N');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'3', N'Documentation', N'A');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'30', N'Database Management', N'K');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'31', N'Database Design', N'K');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'32', N'Data Mining', N'R');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'33', N'Data Analytics', N'E');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'34', N'Compiling Statistics', N'P');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'35', N'Big Data', N'F');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'36', N'Algorithms', N'V');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'37', N'Account Management', N'C');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'38', N'Project Management', N'B');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'39', N'Web Design', N'J');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'4', N'Enterprise Systems', N'A');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'40', N'Project Planning', N'F');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'41', N'Food, Nutrition and Health', N'W');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'42', N'Global Resource Systems', N'T');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'43', N'Food and Resource Economics', N'S');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'44', N'Internation Relations', N'M');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'45', N'Accounting', N'U');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'46', N'Architecture', N'A');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'47', N'Building and Construction', N'M');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'48', N'Marketing', N'G');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'49', N'Document Writing', N'R');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'5', N'Law', N'I');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'50', N'Design and Media', N'J');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'51', N'Paramedicine', N'T');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'52', N'Medicine', N'E');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'53', N'Information Technology', N'Y');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'54', N'Marine Biology', N'L');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'55', N'Marine Engineering', N'F');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'6', N'Data Engineering', N'W');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'7', N'Bridge Construction', N'F');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'8', N'Mechanics', N'W');
INSERT INTO SkillCategory (SkillCategoryId, Label, SortValue) VALUES (N'9', N'Aritificial Intelligence', N'V');