INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'1', N'1', N'Planting', N'B');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'1', N'2', N'Harvesting', N'E');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'1', N'3', N'Fertilizing', N'C');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'1', N'4', N'Irrigating', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'1', N'5', N'Soil Preparation', N'A');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'10', N'1', N'Implementation', N'I');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'10', N'2', N'Information Technology', N'I');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'10', N'3', N'ICT (Information and Communications Technology)', N'B');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'10', N'4', N'Infrastructure', N'G');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'11', N'1', N'Languages', N'N');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'11', N'2', N'Maintenance', N'M');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'11', N'3', N'Network Architecture', N'V');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'11', N'4', N'Network Security', N'Y');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'12', N'1', N'Networking', N'Y');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'12', N'2', N'New Technologies', N'T');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'12', N'3', N'Operating Systems', N'X');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'12', N'4', N'Programming', N'B');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'13', N'1', N'Restoration', N'L');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'13', N'2', N'Security', N'W');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'13', N'3', N'Servers', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'13', N'4', N'Software', N'U');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'14', N'1', N'Solution Delivery', N'I');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'14', N'2', N'Storage', N'R');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'14', N'3', N'Structures', N'M');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'14', N'4', N'Systems Analysis', N'L');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'15', N'1', N'Technical Support', N'I');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'15', N'2', N'Technology', N'F');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'15', N'3', N'Testing', N'W');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'15', N'4', N'Tools', N'A');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'16', N'1', N'Training', N'W');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'16', N'2', N'Troubleshooting', N'E');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'16', N'3', N'Usability', N'V');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'16', N'4', N'Benchmarking', N'M');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'17', N'1', N'Budget Planning', N'Y');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'17', N'2', N'Engineering', N'G');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'17', N'3', N'Fabrication', N'B');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'17', N'4', N'Following Specifications', N'J');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'18', N'1', N'Operations', N'F');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'18', N'2', N'Performance Review', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'18', N'3', N'Project Planning', N'G');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'18', N'4', N'Quality Assurance', N'Y');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'19', N'1', N'Quality Control', N'L');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'19', N'2', N'Scheduling', N'N');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'19', N'3', N'Task Delegation', N'R');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'19', N'4', N'Task Management', N'G');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'2', N'1', N'Transaction Processing', N'A');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'2', N'2', N'Reconciling', N'A');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'2', N'3', N'Auditing', N'A');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'20', N'1', N'Content Management Systems (CMS)', N'B');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'20', N'2', N'Blogging', N'I');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'20', N'3', N'Digital Photography', N'U');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'20', N'4', N'Digital Media', N'R');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'21', N'1', N'Networking', N'L');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'21', N'2', N'Search Engine Optimization (SEO)', N'V');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'21', N'3', N'Social Media Platforms (Twitter, Facebook, Instagram, LinkedIn, TikTok, Medium, etc.)', N'R');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'21', N'4', N'Web Analytics', N'Y');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'22', N'1', N'Automated Marketing Software', N'R');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'22', N'2', N'Client Relations', N'G');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'22', N'3', N'Email', N'T');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'22', N'4', N'Requirements Gathering', N'E');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'23', N'1', N'Research', N'P');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'23', N'2', N'Subject Matter Experts (SMEs)', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'23', N'3', N'Technical Documentation', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'23', N'4', N'Information Security', N'U');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'24', N'1', N'Microsoft Office Certifications', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'24', N'2', N'Video Creation', N'T');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'24', N'3', N'Customer Relationship Management (CRM)', N'C');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'24', N'4', N'Productivity Software', N'C');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'25', N'1', N'Cloud/SaaS Services', N'J');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'25', N'2', N'Database Management', N'C');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'25', N'3', N'Telecommunications', N'S');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'25', N'4', N'Human Resources Software', N'L');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'26', N'1', N'Accounting Software', N'L');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'26', N'2', N'Enterprise Resource Planning (ERP) Software', N'H');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'26', N'3', N'Database Software', N'N');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'26', N'4', N'Query Software', N'B');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'27', N'1', N'Blueprint Design', N'J');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'27', N'2', N'Medical Billing', N'V');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'27', N'3', N'Medical Coding', N'C');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'27', N'4', N'Sonography', N'N');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'28', N'1', N'Structural Analysis', N'S');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'28', N'2', N'Artificial Intelligence (AI)', N'Y');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'28', N'3', N'Mechanical Maintenance', N'C');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'28', N'4', N'Manufacturing', N'S');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'29', N'1', N'Inventory Management', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'29', N'2', N'Numeracy', N'X');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'29', N'3', N'Information Management', N'G');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'29', N'4', N'Hardware Verification Tools and Techniques', N'T');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'3', N'1', N'Planning', N'A');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'3', N'2', N'Budgeting', N'A');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'3', N'3', N'Performance Reviews', N'A');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'30', N'1', N'Hardware Description Language (HDL)', N'E');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'30', N'2', N'Git', N'O');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'30', N'3', N'GitLab', N'M');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'30', N'4', N'GitHub', N'L');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'31', N'1', N'Bitbucket', N'F');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'31', N'2', N'Ansible', N'P');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'31', N'3', N'Jenkins', N'M');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'31', N'4', N'Chef', N'U');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'32', N'1', N'Puppet', N'R');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'32', N'2', N'Kubernetes', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'32', N'3', N'Docker', N'O');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'32', N'4', N'Slack', N'K');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'33', N'1', N'Microsoft Teams', N'E');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'33', N'2', N'Zoom', N'I');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'33', N'3', N'GoToMeeting', N'O');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'33', N'4', N'Skype', N'R');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'34', N'1', N'AWS', N'I');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'34', N'2', N'Azure', N'B');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'34', N'3', N'GCP', N'Y');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'34', N'4', N'Raygun', N'W');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'35', N'1', N'SignalFx', N'B');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'35', N'2', N'Splunk Cloud', N'J');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'35', N'3', N'AppDynamics', N'I');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'35', N'4', N'Catchpoint', N'O');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'36', N'1', N'VictorOps', N'W');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'36', N'2', N'Selenium', N'X');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'36', N'3', N'Cypress', N'E');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'36', N'4', N'Gremlin', N'J');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'37', N'1', N'ServiceNow', N'T');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'37', N'2', N'Statuspage', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'37', N'3', N'4th Dimension/4D', N'J');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'37', N'4', N'ABAP', N'W');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'38', N'1', N'ABC', N'F');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'38', N'2', N'ActionScript', N'B');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'38', N'3', N'Ada', N'P');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'38', N'4', N'Agilent VEE', N'N');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'39', N'1', N'Algol', N'I');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'39', N'2', N'Alice', N'A');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'39', N'3', N'Angelscript', N'Y');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'39', N'4', N'Apex', N'O');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'4', N'1', N'Preparing Marketing Materials', N'A');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'4', N'2', N'Customer Service', N'A');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'4', N'3', N'Marketing Strategies', N'A');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'40', N'1', N'APL', N'N');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'40', N'2', N'AppleScript', N'L');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'40', N'3', N'Arc', N'B');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'40', N'4', N'Arduino', N'X');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'41', N'1', N'ASP', N'A');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'41', N'2', N'AspectJ', N'K');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'41', N'3', N'Assembly', N'C');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'41', N'4', N'ATLAS', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'42', N'1', N'Augeas', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'42', N'2', N'AutoHotkey', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'42', N'3', N'AutoIt', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'42', N'4', N'AutoLISP', N'U');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'43', N'1', N'Automator', N'R');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'43', N'2', N'Avenue', N'C');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'43', N'3', N'Awk', N'L');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'43', N'4', N'Bash', N'N');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'44', N'1', N'(Visual) Basic', N'Y');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'44', N'2', N'bc', N'Q');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'44', N'3', N'BCPL', N'H');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'44', N'4', N'BETA', N'Y');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'45', N'1', N'BlitzMax', N'E');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'45', N'2', N'Boo', N'V');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'45', N'3', N'Bourne Shell', N'T');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'45', N'4', N'Bro', N'H');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'46', N'1', N'C', N'M');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'46', N'2', N'C Shell', N'J');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'46', N'3', N'C#', N'X');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'46', N'4', N'C++', N'U');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'47', N'1', N'C++/CLI', N'K');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'47', N'2', N'C-Omega', N'T');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'47', N'3', N'Caml', N'B');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'47', N'4', N'Ceylon', N'B');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'48', N'1', N'CFML', N'U');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'48', N'2', N'cg', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'48', N'3', N'Ch', N'C');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'48', N'4', N'CHILL', N'H');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'49', N'1', N'CIL', N'A');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'49', N'2', N'CL (OS/400)', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'49', N'3', N'Clarion', N'H');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'49', N'4', N'Clean', N'F');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'5', N'1', N'IDE', N'O');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'5', N'2', N'Frameworks', N'T');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'5', N'3', N'Cloud Tools', N'B');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'5', N'4', N'Data Science', N'N');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'50', N'1', N'Clipper', N'O');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'50', N'2', N'Clojure', N'T');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'50', N'3', N'CLU', N'X');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'50', N'4', N'COBOL', N'I');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'51', N'1', N'Cobra', N'S');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'51', N'2', N'CoffeeScript', N'H');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'51', N'3', N'ColdFusion', N'X');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'51', N'4', N'COMAL', N'U');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'52', N'1', N'Common Lisp', N'I');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'52', N'2', N'Coq', N'T');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'52', N'3', N'cT', N'H');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'52', N'4', N'Curl', N'K');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'53', N'1', N'D', N'L');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'53', N'2', N'Dart', N'R');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'53', N'3', N'DCL', N'C');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'53', N'4', N'DCPU-16 ASM', N'K');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'54', N'1', N'Delphi/Object Pascal', N'K');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'54', N'2', N'DiBOL', N'M');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'54', N'3', N'Dylan', N'E');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'54', N'4', N'E', N'I');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'55', N'1', N'eC', N'F');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'55', N'2', N'Ecl', N'Y');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'55', N'3', N'ECMAScript', N'K');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'55', N'4', N'EGL', N'C');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'6', N'1', N'Source Control', N'A');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'6', N'2', N'Prototyping', N'F');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'6', N'3', N'DevOps', N'O');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'6', N'4', N'Notifications', N'B');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'7', N'1', N'UML', N'T');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'7', N'2', N'Applications', N'R');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'7', N'3', N'Certifications', N'F');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'7', N'4', N'Coding', N'L');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'8', N'1', N'Computing', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'8', N'2', N'Configuration', N'D');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'8', N'3', N'Customer Support', N'J');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'8', N'4', N'Debugging', N'J');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'9', N'1', N'Design', N'E');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'9', N'2', N'Development', N'K');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'9', N'3', N'Hardware', N'V');
INSERT INTO Skill (SkillCategoryId, SkillId, Label, SortValue) VALUES (N'9', N'4', N'HTML', N'S');