INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'01', N'01', N'01', N'Administration', N'10002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'01', N'01', N'02', N'Marketing', N'10003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'01', N'01', N'03', N'Sales', N'10004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'01', N'01', N'04', N'Accounting', N'10005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'01', N'01', N'05', N'Human Resources', N'10005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'02', N'01', N'02', N'Administration', N'20006');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'02', N'01', N'03', N'Marketing', N'20003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'02', N'02', N'04', N'Sales', N'20004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'02', N'02', N'05', N'Service', N'20005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'03', N'03', N'03', N'Administration', N'30012');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'03', N'03', N'04', N'Marketing & Sales', N'30023');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'03', N'03', N'05', N'Distribution', N'30024');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'03', N'04', N'08', N'Operations', N'30025');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'10', N'1', N'1', N'International Affairs', N'40001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'10', N'1', N'2', N'Beer, Wine, and Liquor Stores', N'40002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'10', N'1', N'3', N'Other Personal and Household Goods Repair and Maintenance', N'40003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'10', N'1', N'5', N'Management Consulting Services', N'40005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'10', N'3', N'4', N'Hair, Nail, and Skin Care Services', N'40004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'11', N'1', N'1', N'Synthetic Dye and Pigment Manufacturing', N'41001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'11', N'1', N'4', N'Soap and Cleaning Compound Manufacturing', N'41004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'11', N'1', N'5', N'Other Concrete Product Manufacturing', N'41005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'11', N'2', N'2', N'Electric Lamp Bulb and Part Manufacturing', N'41002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'11', N'3', N'3', N'Cement Manufacturing', N'41003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'12', N'1', N'1', N'Cosmetics, Beauty Supplies, and Perfume Stores', N'42001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'12', N'1', N'4', N'Paper Bag and Coated and Treated Paper Manufacturing', N'42004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'12', N'1', N'5', N'Broilers and Other Meat Type Chicken Production', N'42005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'12', N'3', N'2', N'Office Furniture (including Fixtures) Manufacturing', N'42002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'12', N'3', N'3', N'Sound Recording Studios', N'42003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'13', N'1', N'2', N'Electronic and Precision Equipment Repair and Maintenance', N'43002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'13', N'2', N'3', N'Other Electronic Parts and Equipment Merchant Wholesalers', N'43003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'13', N'2', N'4', N'Other General Government Support', N'43004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'13', N'3', N'1', N'Fish and Seafood', N'43001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'13', N'3', N'5', N'Commercial Banking', N'43005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'14', N'1', N'1', N'Elementary and Secondary Schools', N'44001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'14', N'1', N'2', N'Stationery Product Manufacturing', N'44002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'14', N'2', N'3', N'Lessors of Other Real Estate Property', N'44003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'14', N'2', N'4', N'Flooring Contractors', N'44004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'14', N'3', N'5', N'Metal Can, Box, and Other Metal Container', N'44005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'15', N'1', N'1', N'Children''s and Infants'' Clothing Stores', N'45001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'15', N'1', N'5', N'Computer and Peripheral Equipment Manufacturing', N'45005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'15', N'2', N'4', N'Optical Goods Stores', N'45004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'15', N'3', N'2', N'All General Purpose Machinery Manufacturing', N'45002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'15', N'3', N'3', N'Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)', N'45003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'16', N'1', N'4', N'Civic and Social Organizations', N'46004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'16', N'2', N'1', N'Inland Water Transportation', N'46001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'16', N'2', N'5', N'Horses Production', N'46005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'16', N'3', N'2', N'Leather and Hide Tanning and Finishing', N'46002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'16', N'3', N'3', N'Limo Service', N'46003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'17', N'1', N'2', N'Other Activities Related to Credit Intermediation', N'47002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'17', N'1', N'3', N'Savings Institutions', N'47003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'17', N'1', N'5', N'Offices of Physicians', N'47005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'17', N'2', N'1', N'Cut and Sew Apparel Contractors', N'47001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'17', N'2', N'4', N'Sewing, Needlework, and Piece Goods Stores', N'47004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'18', N'1', N'1', N'Credit Card Issuing', N'48001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'18', N'1', N'2', N'Ferrous Metal Foundries', N'48002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'18', N'2', N'4', N'Wood Kitchen Cabinet and Countertop Manufacturing', N'48004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'18', N'3', N'3', N'Wiring Device Manufacturing', N'48003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'18', N'3', N'5', N'Book Publishers', N'48005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'19', N'1', N'1', N'All Other Specialty Trade Contractors', N'49001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'19', N'1', N'4', N'Piece Goods, Notions, and Other Dry Goods Merchant Wholesalers', N'49004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'19', N'2', N'2', N'Vegetable and Melon Farming', N'49002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'19', N'2', N'3', N'Knit Fabric Mills', N'49003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'19', N'3', N'5', N'Other Grocery and Related Products Merchant Wholesalers', N'49005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'20', N'2', N'2', N'Heavy Duty Truck Manufacturing', N'50002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'20', N'2', N'3', N'Political Organizations', N'50003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'20', N'2', N'5', N'Administration of Urban Planning and Community and Rural Development', N'50005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'20', N'3', N'1', N'Forest Nurseries and Gathering of Forest Products', N'50001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'20', N'3', N'4', N'Plumbing and Heating Equipment and Supplies (Hydronics) Merchant Wholesalers', N'50004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'21', N'1', N'3', N'Industrial Machinery and Equipment Merchant Wholesalers', N'51003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'21', N'2', N'1', N'Lime Manufacturing', N'51001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'21', N'2', N'2', N'Plate Work and Fabricated Structural Product Manufacturing', N'51002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'21', N'3', N'4', N'Other Depository Credit Intermediation', N'51004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'21', N'3', N'5', N'Other Transit and Ground Passenger Transportation', N'51005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'22', N'1', N'1', N'Goat Farming', N'52001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'22', N'2', N'2', N'Port Operations', N'52002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'22', N'2', N'4', N'General Line Grocery Merchant Wholesalers', N'52004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'22', N'2', N'5', N'All Fabricated Metal Product Manufacturing', N'52005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'22', N'3', N'3', N'News Syndicates', N'52003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'23', N'1', N'1', N'Record Production', N'53001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'23', N'1', N'5', N'Interurban and Rural Bus Transportation', N'53005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'23', N'2', N'3', N'Farm Product Warehousing and Storage', N'53003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'23', N'3', N'2', N'Scenic and Sightseeing Transportation, Land', N'53002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'23', N'3', N'4', N'Photographic Equipment and Supplies Merchant Wholesalers', N'53004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'24', N'1', N'1', N'Residential Building Construction', N'54001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'24', N'1', N'4', N'Office Machinery and Equipment Rental and Leasing', N'54004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'24', N'2', N'2', N'Doll, Toy, and Game Manufacturing', N'54002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'24', N'2', N'5', N'Technical and Trade Schools', N'54005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'24', N'3', N'3', N'Dairy and Milk Production', N'54003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'25', N'2', N'3', N'Fine Arts Schools', N'55003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'25', N'2', N'4', N'Metalworking Machinery Manufacturing', N'55004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'25', N'2', N'5', N'Metal Service Centers and Other Metal Merchant Wholesalers', N'55005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'25', N'3', N'1', N'Industrial Gas Manufacturing', N'55001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'25', N'3', N'2', N'Regulation, Licensing, and Inspection of Miscellaneous Commercial Sectors', N'55002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'26', N'1', N'2', N'Other Traveler Accommodation', N'56002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'26', N'1', N'3', N'Navigational, Measuring, Electromedical, and Control Instruments Manufacturing', N'56003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'26', N'1', N'5', N'Wood Container and Pallet Manufacturing', N'56005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'26', N'2', N'1', N'Other Insurance Funds', N'56001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'26', N'2', N'4', N'Research and Development in the Physical, Engineering, and Life Sciences', N'56004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'27', N'2', N'4', N'Casino Hotels', N'57004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'27', N'2', N'5', N'Petroleum and Petroleum Products Merchant Wholesalers (except Bulk Stations and Terminals)', N'57005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'27', N'3', N'1', N'Administration of Veterans'' Affairs', N'57001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'27', N'3', N'2', N'Flower, Nursery Stock, and Florists'' Supplies Merchant Wholesalers', N'57002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'27', N'3', N'3', N'Lessors of Residential Buildings and Dwellings', N'57003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'28', N'1', N'3', N'All Other Professional, Scientific, and Technical Services', N'58003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'28', N'1', N'4', N'Seasoning and Dressing Manufacturing', N'58004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'28', N'3', N'1', N'Home Health Care Services', N'58001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'28', N'3', N'2', N'Home Furnishing Merchant Wholesalers', N'58002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'28', N'3', N'5', N'Sewage Treatment Facilities', N'58005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'29', N'1', N'2', N'Other Chemical and Allied Products Merchant Wholesalers', N'59002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'29', N'1', N'3', N'Architectural Services', N'59003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'29', N'2', N'1', N'Other Telecommunications', N'59001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'29', N'2', N'5', N'Turkey Production', N'59005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'29', N'3', N'4', N'Distilleries', N'59004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'30', N'1', N'1', N'Zoos and Botanical Gardens', N'60001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'30', N'2', N'2', N'Health and Welfare Funds', N'60002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'30', N'2', N'3', N'Other Heavy and Civil Engineering Construction', N'60003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'30', N'2', N'4', N'Data Processing, Hosting, and Related Services', N'60004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'30', N'2', N'5', N'Footwear Merchant Wholesalers', N'60005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'31', N'1', N'2', N'Poultry and Poultry Product Merchant Wholesalers', N'61002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'31', N'1', N'3', N'Laminated Plastics Plate, Sheet (except Packaging), and Shape Manufacturing', N'61003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'31', N'1', N'4', N'Limousine Service', N'61004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'31', N'2', N'5', N'Fish and Seafood Merchant Wholesalers', N'61005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'31', N'3', N'1', N'Wholesale Trade Agents and Brokers', N'61001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'32', N'1', N'4', N'Gypsum Product Manufacturing', N'62004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'32', N'1', N'5', N'Open-End Investment Funds', N'62005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'32', N'2', N'1', N'Breweries', N'62001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'32', N'2', N'2', N'Urethane and Other Foam Product (except Polystyrene) Manufacturing', N'62002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'32', N'2', N'3', N'Automobile and Other Motor Vehicle Merchant Wholesalers', N'62003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'33', N'1', N'3', N'Convention and Trade Show Organizers', N'63003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'33', N'1', N'4', N'Pet Care (except Veterinary) Services', N'63004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'33', N'2', N'5', N'Fish and Seafood Markets', N'63005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'33', N'3', N'1', N'Tobacco Product Manufacturing', N'63001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'33', N'3', N'2', N'Airport Operations', N'63002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'34', N'2', N'2', N'Language Schools', N'64002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'34', N'2', N'5', N'Scheduled Air Transportation', N'64005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'34', N'3', N'1', N'Used Merchandise Stores', N'64001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'34', N'3', N'3', N'Metal Can, Box, and Other Metal Container (Light Gauge) Manufacturing', N'64003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'34', N'3', N'4', N'Dairy Cattle and Milk Production', N'64004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'35', N'1', N'1', N'Noncitrus Fruit and Tree Nut Farming', N'65001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'35', N'1', N'2', N'Rice Farming', N'65002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'35', N'1', N'4', N'Offices of Chiropractors', N'65004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'35', N'2', N'3', N'Ice Cream and Frozen Dessert Manufacturing', N'65003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'35', N'2', N'5', N'Audio and Video Equipment Manufacturing', N'65005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'36', N'2', N'1', N'Tour Operators', N'66001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'36', N'2', N'2', N'All Other General Purpose Machinery Manufacturing', N'66002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'36', N'2', N'3', N'All Other Animal Production', N'66003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'36', N'3', N'4', N'Horses and Other Equine Production', N'66004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'36', N'3', N'5', N'Charter Bus Industry', N'66005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'37', N'1', N'5', N'Meat Markets', N'67005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'37', N'2', N'1', N'Fruit and Vegetable Markets', N'67001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'37', N'2', N'2', N'Local Messengers and Local Delivery', N'67002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'37', N'2', N'3', N'Commodity Contracts Brokerage', N'67003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'37', N'3', N'4', N'Paint, Varnish, and Supplies Merchant Wholesalers', N'67004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'38', N'1', N'1', N'Motor Vehicle Brake System Manufacturing', N'68001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'38', N'1', N'3', N'Gasoline Stations with Convenience Stores', N'68003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'38', N'2', N'2', N'Orange Groves', N'68002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'38', N'2', N'4', N'Regulation of Agricultural Marketing and Commodities', N'68004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'38', N'3', N'5', N'Material Handling Equipment Manufacturing', N'68005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'39', N'2', N'4', N'Other Electronic Parts Wholesalers', N'69004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'39', N'2', N'5', N'Community Food Services', N'69005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'39', N'3', N'1', N'All Other Fabricated Metal Product Manufacturing', N'69001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'39', N'3', N'2', N'Fabric Coating Mills', N'69002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'39', N'3', N'3', N'Port and Harbor Operations', N'69003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'40', N'1', N'1', N'International Affairs', N'70001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'40', N'1', N'4', N'Hair, Nail, and Skin Care Services', N'70004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'40', N'2', N'5', N'Management Consulting Services', N'70005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'40', N'3', N'2', N'Beer, Wine, and Liquor Stores', N'70002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'40', N'3', N'3', N'Other Personal and Household Goods Repair and Maintenance', N'70003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'41', N'1', N'1', N'Synthetic Dye and Pigment Manufacturing', N'71001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'41', N'1', N'3', N'Cement Manufacturing', N'71003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'41', N'1', N'5', N'Other Concrete Product Manufacturing', N'71005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'41', N'2', N'2', N'Electric Lamp Bulb and Part Manufacturing', N'71002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'41', N'3', N'4', N'Soap and Cleaning Compound Manufacturing', N'71004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'42', N'1', N'4', N'Paper Bag and Coated and Treated Paper Manufacturing', N'72004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'42', N'2', N'1', N'Cosmetics, Beauty Supplies, and Perfume Stores', N'72001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'42', N'2', N'2', N'Office Furniture (including Fixtures) Manufacturing', N'72002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'42', N'2', N'3', N'Sound Recording Studios', N'72003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'42', N'3', N'5', N'Broilers and Other Meat Type Chicken Production', N'72005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'43', N'2', N'1', N'Fish and Seafood', N'73001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'43', N'2', N'3', N'Other Electronic Parts and Equipment Merchant Wholesalers', N'73003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'43', N'2', N'5', N'Commercial Banking', N'73005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'43', N'3', N'2', N'Electronic and Precision Equipment Repair and Maintenance', N'73002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'43', N'3', N'4', N'Other General Government Support', N'73004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'44', N'1', N'1', N'Elementary and Secondary Schools', N'74001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'44', N'1', N'2', N'Stationery Product Manufacturing', N'74002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'44', N'1', N'3', N'Lessors of Other Real Estate Property', N'74003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'44', N'3', N'4', N'Flooring Contractors', N'74004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'44', N'3', N'5', N'Metal Can, Box, and Other Metal Container', N'74005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'45', N'1', N'2', N'All General Purpose Machinery Manufacturing', N'75002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'45', N'1', N'3', N'Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)', N'75003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'45', N'1', N'5', N'Computer and Peripheral Equipment Manufacturing', N'75005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'45', N'3', N'1', N'Children''s and Infants'' Clothing Stores', N'75001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'45', N'3', N'4', N'Optical Goods Stores', N'75004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'46', N'1', N'5', N'Horses Production', N'76005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'46', N'2', N'3', N'Limo Service', N'76003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'46', N'2', N'4', N'Civic and Social Organizations', N'76004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'46', N'3', N'1', N'Inland Water Transportation', N'76001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'46', N'3', N'2', N'Leather and Hide Tanning and Finishing', N'76002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'47', N'2', N'1', N'Cut and Sew Apparel Contractors', N'77001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'47', N'2', N'2', N'Other Activities Related to Credit Intermediation', N'77002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'47', N'2', N'5', N'Offices of Physicians', N'77005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'47', N'3', N'3', N'Savings Institutions', N'77003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'47', N'3', N'4', N'Sewing, Needlework, and Piece Goods Stores', N'77004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'48', N'1', N'2', N'Ferrous Metal Foundries', N'78002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'48', N'2', N'3', N'Wiring Device Manufacturing', N'78003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'48', N'2', N'4', N'Wood Kitchen Cabinet and Countertop Manufacturing', N'78004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'48', N'2', N'5', N'Book Publishers', N'78005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'48', N'3', N'1', N'Credit Card Issuing', N'78001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'49', N'2', N'1', N'All Other Specialty Trade Contractors', N'79001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'49', N'2', N'4', N'Piece Goods, Notions, and Other Dry Goods Merchant Wholesalers', N'79004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'49', N'3', N'2', N'Vegetable and Melon Farming', N'79002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'49', N'3', N'3', N'Knit Fabric Mills', N'79003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'49', N'3', N'5', N'Other Grocery and Related Products Merchant Wholesalers', N'79005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'50', N'1', N'2', N'Heavy Duty Truck Manufacturing', N'80002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'50', N'1', N'5', N'Administration of Urban Planning and Community and Rural Development', N'80005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'50', N'3', N'1', N'Forest Nurseries and Gathering of Forest Products', N'80001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'50', N'3', N'3', N'Political Organizations', N'80003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'50', N'3', N'4', N'Plumbing and Heating Equipment and Supplies (Hydronics) Merchant Wholesalers', N'80004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'51', N'1', N'5', N'Other Transit and Ground Passenger Transportation', N'81005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'51', N'2', N'2', N'Plate Work and Fabricated Structural Product Manufacturing', N'81002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'51', N'3', N'1', N'Lime Manufacturing', N'81001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'51', N'3', N'3', N'Industrial Machinery and Equipment Merchant Wholesalers', N'81003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'51', N'3', N'4', N'Other Depository Credit Intermediation', N'81004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'52', N'1', N'1', N'Goat Farming', N'82001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'52', N'1', N'2', N'Port Operations', N'82002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'52', N'2', N'4', N'General Line Grocery Merchant Wholesalers', N'82004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'52', N'3', N'3', N'News Syndicates', N'82003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'52', N'3', N'5', N'All Fabricated Metal Product Manufacturing', N'82005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'53', N'1', N'1', N'Record Production', N'83001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'53', N'1', N'5', N'Interurban and Rural Bus Transportation', N'83005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'53', N'3', N'2', N'Scenic and Sightseeing Transportation, Land', N'83002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'53', N'3', N'3', N'Farm Product Warehousing and Storage', N'83003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'53', N'3', N'4', N'Photographic Equipment and Supplies Merchant Wholesalers', N'83004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'54', N'1', N'3', N'Dairy and Milk Production', N'84003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'54', N'1', N'4', N'Office Machinery and Equipment Rental and Leasing', N'84004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'54', N'1', N'5', N'Technical and Trade Schools', N'84005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'54', N'2', N'2', N'Doll, Toy, and Game Manufacturing', N'84002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'54', N'3', N'1', N'Residential Building Construction', N'84001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'55', N'1', N'2', N'Regulation, Licensing, and Inspection of Miscellaneous Commercial Sectors', N'85002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'55', N'1', N'4', N'Metalworking Machinery Manufacturing', N'85004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'55', N'2', N'3', N'Fine Arts Schools', N'85003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'55', N'2', N'5', N'Metal Service Centers and Other Metal Merchant Wholesalers', N'85005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'55', N'3', N'1', N'Industrial Gas Manufacturing', N'85001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'56', N'1', N'3', N'Navigational, Measuring, Electromedical, and Control Instruments Manufacturing', N'86003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'56', N'1', N'5', N'Wood Container and Pallet Manufacturing', N'86005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'56', N'3', N'1', N'Other Insurance Funds', N'86001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'56', N'3', N'2', N'Other Traveler Accommodation', N'86002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'56', N'3', N'4', N'Research and Development in the Physical, Engineering, and Life Sciences', N'86004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'57', N'1', N'3', N'Lessors of Residential Buildings and Dwellings', N'87003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'57', N'2', N'1', N'Administration of Veterans'' Affairs', N'87001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'57', N'3', N'2', N'Flower, Nursery Stock, and Florists'' Supplies Merchant Wholesalers', N'87002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'57', N'3', N'4', N'Casino Hotels', N'87004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'57', N'3', N'5', N'Petroleum and Petroleum Products Merchant Wholesalers (except Bulk Stations and Terminals)', N'87005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'58', N'1', N'2', N'Home Furnishing Merchant Wholesalers', N'88002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'58', N'1', N'5', N'Sewage Treatment Facilities', N'88005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'58', N'2', N'4', N'Seasoning and Dressing Manufacturing', N'88004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'58', N'3', N'1', N'Home Health Care Services', N'88001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'58', N'3', N'3', N'All Other Professional, Scientific, and Technical Services', N'88003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'59', N'1', N'4', N'Distilleries', N'89004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'59', N'2', N'1', N'Other Telecommunications', N'89001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'59', N'3', N'2', N'Other Chemical and Allied Products Merchant Wholesalers', N'89002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'59', N'3', N'3', N'Architectural Services', N'89003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'59', N'3', N'5', N'Turkey Production', N'89005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'60', N'1', N'1', N'Zoos and Botanical Gardens', N'90001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'60', N'1', N'4', N'Data Processing, Hosting, and Related Services', N'90004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'60', N'2', N'3', N'Other Heavy and Civil Engineering Construction', N'90003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'60', N'3', N'2', N'Health and Welfare Funds', N'90002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'60', N'3', N'5', N'Footwear Merchant Wholesalers', N'90005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'61', N'1', N'5', N'Fish and Seafood Merchant Wholesalers', N'91005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'61', N'2', N'2', N'Poultry and Poultry Product Merchant Wholesalers', N'91002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'61', N'2', N'3', N'Laminated Plastics Plate, Sheet (except Packaging), and Shape Manufacturing', N'91003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'61', N'2', N'4', N'Limousine Service', N'91004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'61', N'3', N'1', N'Wholesale Trade Agents and Brokers', N'91001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'62', N'1', N'4', N'Gypsum Product Manufacturing', N'92004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'62', N'1', N'5', N'Open-End Investment Funds', N'92005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'62', N'2', N'1', N'Breweries', N'92001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'62', N'2', N'3', N'Automobile and Other Motor Vehicle Merchant Wholesalers', N'92003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'62', N'3', N'2', N'Urethane and Other Foam Product (except Polystyrene) Manufacturing', N'92002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'63', N'1', N'3', N'Convention and Trade Show Organizers', N'93003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'63', N'1', N'5', N'Fish and Seafood Markets', N'93005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'63', N'2', N'2', N'Airport Operations', N'93002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'63', N'3', N'1', N'Tobacco Product Manufacturing', N'93001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'63', N'3', N'4', N'Pet Care (except Veterinary) Services', N'93004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'64', N'1', N'1', N'Used Merchandise Stores', N'94001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'64', N'1', N'2', N'Language Schools', N'94002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'64', N'2', N'3', N'Metal Can, Box, and Other Metal Container (Light Gauge) Manufacturing', N'94003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'64', N'3', N'4', N'Dairy Cattle and Milk Production', N'94004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'64', N'3', N'5', N'Scheduled Air Transportation', N'94005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'65', N'2', N'1', N'Noncitrus Fruit and Tree Nut Farming', N'95001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'65', N'2', N'2', N'Rice Farming', N'95002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'65', N'2', N'3', N'Ice Cream and Frozen Dessert Manufacturing', N'95003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'65', N'2', N'5', N'Audio and Video Equipment Manufacturing', N'95005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'65', N'3', N'4', N'Offices of Chiropractors', N'95004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'66', N'1', N'2', N'All Other General Purpose Machinery Manufacturing', N'96002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'66', N'3', N'1', N'Tour Operators', N'96001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'66', N'3', N'3', N'All Other Animal Production', N'96003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'66', N'3', N'4', N'Horses and Other Equine Production', N'96004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'66', N'3', N'5', N'Charter Bus Industry', N'96005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'67', N'1', N'2', N'Local Messengers and Local Delivery', N'97002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'67', N'1', N'5', N'Meat Markets', N'97005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'67', N'2', N'3', N'Commodity Contracts Brokerage', N'97003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'67', N'2', N'4', N'Paint, Varnish, and Supplies Merchant Wholesalers', N'97004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'67', N'3', N'1', N'Fruit and Vegetable Markets', N'97001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'68', N'1', N'5', N'Material Handling Equipment Manufacturing', N'98005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'68', N'2', N'3', N'Gasoline Stations with Convenience Stores', N'98003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'68', N'2', N'4', N'Regulation of Agricultural Marketing and Commodities', N'98004');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'68', N'3', N'1', N'Motor Vehicle Brake System Manufacturing', N'98001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'68', N'3', N'2', N'Orange Groves', N'98002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'69', N'1', N'2', N'Fabric Coating Mills', N'99002');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'69', N'1', N'3', N'Port and Harbor Operations', N'99003');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'69', N'1', N'5', N'Community Food Services', N'99005');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'69', N'3', N'1', N'All Other Fabricated Metal Product Manufacturing', N'99001');
INSERT INTO LocationGroup (CompanyCode, OfficeCode, GroupCode, Label, ManagerWorkerNumber) VALUES (N'69', N'3', N'4', N'Other Electronic Parts Wholesalers', N'99004');