INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'01', N'01', N'Corporate', N'10001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'02', N'01', N'Vancouver', N'20006');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'02', N'02', N'Victoria', N'20002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'03', N'03', N'Kelowna', N'30008');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'03', N'04', N'Prince George', N'30012');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'10', N'1', N'Phoenix ', N'40001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'10', N'2', N'New Hope ', N'40002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'10', N'3', N'Kaneohe ', N'40003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'11', N'1', N'Ecorse ', N'41001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'11', N'2', N'Monmouth ', N'41002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'11', N'3', N'Beverly ', N'41003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'12', N'1', N'Port Gibson ', N'42001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'12', N'2', N'Madison ', N'42002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'12', N'3', N'Montclair ', N'42003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'13', N'1', N'Shelby ', N'43001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'13', N'2', N'Silver Spring ', N'43002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'13', N'3', N'Woonsocket ', N'43003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'14', N'1', N'Nanticoke ', N'44001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'14', N'2', N'Saint Johnsbury ', N'44002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'14', N'3', N'Asheville ', N'44003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'15', N'1', N'Barrington ', N'45001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'15', N'2', N'Castine ', N'45002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'15', N'3', N'Grinnell ', N'45003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'16', N'1', N'Waterbury ', N'46001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'16', N'2', N'Blackfoot ', N'46002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'16', N'3', N'Lewiston ', N'46003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'17', N'1', N'Kenosha ', N'47001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'17', N'2', N'Sanford ', N'47002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'17', N'3', N'Cranford ', N'47003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'18', N'1', N'Gloversville ', N'48001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'18', N'2', N'Honolulu ', N'48002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'18', N'3', N'South Kingstown ', N'48003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'19', N'1', N'Hattiesburg ', N'49001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'19', N'2', N'Hollywood ', N'49002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'19', N'3', N'Dothan ', N'49003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'20', N'1', N'Exeter ', N'50001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'20', N'2', N'Alhambra ', N'50002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'20', N'3', N'Sierra Vista ', N'50003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'21', N'1', N'North Haven ', N'51001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'21', N'2', N'Lombard ', N'51002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'21', N'3', N'Greensburg ', N'51003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'22', N'1', N'Fort Payne ', N'52001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'22', N'2', N'Asbury Park ', N'52002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'22', N'3', N'Park Forest ', N'52003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'23', N'1', N'Bainbridge ', N'53001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'23', N'2', N'Tallahassee ', N'53002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'23', N'3', N'Santa Monica ', N'53003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'24', N'1', N'Watertown ', N'54001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'24', N'2', N'Frederick ', N'54002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'24', N'3', N'Hartsville ', N'54003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'25', N'1', N'Yonkers ', N'55001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'25', N'2', N'El Reno ', N'55002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'25', N'3', N'Bisbee ', N'55003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'26', N'1', N'Thibodaux ', N'56001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'26', N'2', N'South Bend ', N'56002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'26', N'3', N'Truth or Consequences ', N'56003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'27', N'1', N'Hanover ', N'57001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'27', N'2', N'Taos ', N'57002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'27', N'3', N'Roselle ', N'57003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'28', N'1', N'Laredo ', N'58001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'28', N'2', N'Hugo ', N'58002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'28', N'3', N'San Rafael ', N'58003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'29', N'1', N'Wilmington ', N'59001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'29', N'2', N'Garland ', N'59002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'29', N'3', N'Manchester ', N'59003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'30', N'1', N'Huron ', N'60001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'30', N'2', N'Des Plaines ', N'60002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'30', N'3', N'Perth Amboy ', N'60003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'31', N'1', N'Youngstown ', N'61001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'31', N'2', N'Ten Sleep ', N'61002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'31', N'3', N'Canyon ', N'61003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'32', N'1', N'Ontario ', N'62001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'32', N'2', N'Shreveport ', N'62002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'32', N'3', N'Alamosa ', N'62003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'33', N'1', N'East Hartford ', N'63001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'33', N'2', N'Macomb ', N'63002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'33', N'3', N'Braintree ', N'63003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'34', N'1', N'Odessa ', N'64001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'34', N'2', N'Vernal ', N'64002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'34', N'3', N'Prichard ', N'64003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'35', N'1', N'Grayling ', N'65001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'35', N'2', N'Murray ', N'65002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'35', N'3', N'Richmond ', N'65003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'36', N'1', N'Muscatine ', N'66001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'36', N'2', N'Monroeville ', N'66002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'36', N'3', N'Santa Clarita ', N'66003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'37', N'1', N'Rockford ', N'67001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'37', N'2', N'Tombstone ', N'67002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'37', N'3', N'New Orleans ', N'67003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'38', N'1', N'Hobart ', N'68001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'38', N'2', N'Florissant ', N'68002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'38', N'3', N'Elwood ', N'68003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'39', N'1', N'Barre ', N'69001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'39', N'2', N'Okmulgee ', N'69002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'39', N'3', N'Lorain ', N'69003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'40', N'1', N'Brattleboro ', N'70001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'40', N'2', N'Flushing ', N'70002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'40', N'3', N'Winslow ', N'70003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'41', N'1', N'New Paltz ', N'71001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'41', N'2', N'Hobbs ', N'71002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'41', N'3', N'Carlisle ', N'71003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'42', N'1', N'Powell ', N'72001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'42', N'2', N'Victoria ', N'72002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'42', N'3', N'Long Beach ', N'72003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'43', N'1', N'Kanab ', N'73001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'43', N'2', N'Smithton ', N'73002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'43', N'3', N'Murray Bridge ', N'73003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'44', N'1', N'Healesville ', N'74001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'44', N'2', N'Mount Isa ', N'74002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'44', N'3', N'Wynyard ', N'74003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'45', N'1', N'Ingham ', N'75001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'45', N'2', N'Temora ', N'75002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'45', N'3', N'Sydney ', N'75003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'46', N'1', N'Tumut ', N'76001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'46', N'2', N'Nambucca Heads ', N'76002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'46', N'3', N'Gunnedah ', N'76003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'47', N'1', N'Horsham ', N'77001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'47', N'2', N'Charters Towers ', N'77002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'47', N'3', N'Dubbo ', N'77003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'48', N'1', N'Tamworth ', N'78001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'48', N'2', N'Maitland ', N'78002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'48', N'3', N'Katherine ', N'78003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'49', N'1', N'Hamilton ', N'79001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'49', N'2', N'Armidale ', N'79002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'49', N'3', N'Bowral ', N'79003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'50', N'1', N'Mount Morgan ', N'80001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'50', N'2', N'Adelaide ', N'80002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'50', N'3', N'Canberra ', N'80003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'51', N'1', N'Raymond Terrace ', N'81001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'51', N'2', N'Goondiwindi ', N'81002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'51', N'3', N'Dampier ', N'81003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'52', N'1', N'Broome ', N'82001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'52', N'2', N'Castlemaine ', N'82002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'52', N'3', N'Narrogin ', N'82003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'53', N'1', N'Kurri Kurri ', N'83001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'53', N'2', N'Moree ', N'83002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'53', N'3', N'Darwin ', N'83003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'54', N'1', N'Bega ', N'84001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'54', N'2', N'West Wyalong ', N'84002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'54', N'3', N'Port Hedland ', N'84003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'55', N'1', N'Muswellbrook ', N'85001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'55', N'2', N'Kerang ', N'85002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'55', N'3', N'Wonthaggi ', N'85003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'56', N'1', N'Whyalla ', N'86001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'56', N'2', N'Charleville ', N'86002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'56', N'3', N'Beaconsfield ', N'86003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'57', N'1', N'Forster ', N'87001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'57', N'2', N'Gundagai ', N'87002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'57', N'3', N'Goolwa ', N'87003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'58', N'1', N'Cairns ', N'88001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'58', N'2', N'Wagga Wagga ', N'88002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'58', N'3', N'Shepparton ', N'88003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'59', N'1', N'Warragul ', N'89001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'59', N'2', N'Glen Innes ', N'89002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'59', N'3', N'Taree ', N'89003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'60', N'1', N'Ballina ', N'90001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'60', N'2', N'Northam ', N'90002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'60', N'3', N'Queanbeyan ', N'90003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'61', N'1', N'Colac ', N'91001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'61', N'2', N'Kalgoorlie ', N'91002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'61', N'3', N'Cooma ', N'91003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'62', N'1', N'Nowra-Bomaderry ', N'92001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'62', N'2', N'Moranbah ', N'92002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'62', N'3', N'Loxton ', N'92003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'63', N'1', N'Kingston ', N'93001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'63', N'2', N'Launceston ', N'93002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'63', N'3', N'Ulladulla ', N'93003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'64', N'1', N'Goulburn ', N'94001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'64', N'2', N'Bowen ', N'94002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'64', N'3', N'Wyong ', N'94003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'65', N'1', N'Moe ', N'95001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'65', N'2', N'Traralgon ', N'95002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'65', N'3', N'Lakes Entrance ', N'95003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'66', N'1', N'Mount Gambier ', N'96001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'66', N'2', N'Ceduna ', N'96002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'66', N'3', N'Rosebery ', N'96003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'67', N'1', N'Cootamundra ', N'97001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'67', N'2', N'Maryborough ', N'97002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'67', N'3', N'Devonport ', N'97003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'68', N'1', N'Tom Price ', N'98001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'68', N'2', N'Port Augusta ', N'98002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'68', N'3', N'Narrabri ', N'98003');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'69', N'1', N'Ulverstone ', N'99001');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'69', N'2', N'Echuca ', N'99002');
INSERT INTO LocationOffice (CompanyCode, OfficeCode, Label, ManagerWorkerNumber) VALUES (N'69', N'3', N'Bunbury ', N'99003');