INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'1', N'Vancouver D', N'A');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'AQUBVOYASE', N'Moose Jaw ', N'S');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'ASXEKSRGRC', N'Fredericton ', N'J');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'AYBWXOVBVA', N'Lunenburg ', N'X');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'BIVSDMOWFB', N'Vernon ', N'V');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'BUMXDIRSQK', N'Souris ', N'Y');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'BWOMPPRWUW', N'Trail ', N'L');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'CAAKBFBDXG', N'Estevan ', N'E');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'DAKWBLNKYE', N'Guelph ', N'F');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'DGAHGFTTXI', N'Fort Saint James ', N'B');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'DIVCPWUCFP', N'Ferryland ', N'J');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'DLSRCGRKIN', N'Dawson Creek ', N'K');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'DPAGONLXIU', N'Laval ', N'I');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'DQPBKWAUFT', N'Powell River ', N'X');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'EDQSPMLPBU', N'Kingston ', N'O');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'EICHSGNJDS', N'West Nipissing ', N'V');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'ELXDITJPQT', N'Corner Brook ', N'N');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'EMXOINIOJC', N'Chilliwack ', N'W');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'EVMWKTURWG', N'Oakville ', N'U');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'G', N'Vancouver B', N'A');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'GHHDT', N'Vancouver A', N'A');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'GHHDT1H7', N'Vancouver', N'A');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'GTALDGEWYA', N'Saint Boniface ', N'X');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'H', N'Vancouver C', N'A');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'HARESUFNWD', N'Fort Smith ', N'R');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'HWLJWIAPIU', N'Louisbourg ', N'B');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'ITTLGIABLQ', N'Hamilton ', N'C');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'JGH7T', N'Prince George', N'D');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'JKDPQEELRV', N'Summerside ', N'X');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'JSAAXIRKDO', N'Whitehorse ', N'V');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'KDLKOTNBXM', N'Quesnel ', N'S');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'LBURROIRCQ', N'Winnipeg ', N'J');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'LDFS8F3DDS', N'Kelowna', N'C');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'LDIMAKJWJY', N'Inuvik ', N'K');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'LMGBALXAXU', N'Fort Frances ', N'U');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'LNPHSSLTJM', N'Dorval ', N'U');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'LPBVOALECJ', N'Cranbrook ', N'D');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'MBYPTBFLBH', N'Granby ', N'F');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'MEEFHAHMDB', N'Woodstock ', N'H');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'MFUUQHSPPD', N'Placentia ', N'I');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'MNTNHDORLH', N'La Salle ', N'C');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'NEDCJYEOFN', N'Sydney ', N'M');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'OCJRQPJUMF', N'Cavendish ', N'G');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'OVLSHUQSMY', N'Waterloo ', N'R');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'QRKURWEDQG', N'Moose Factory ', N'P');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'QTCRDKPROA', N'Yarmouth ', N'W');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'QWXVSUSETO', N'Havre-Saint-Pierre ', N'Y');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'RAMUCMFTTW', N'Trois-Rivi ', N'R');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'RRXDAPTRLL', N'White Rock ', N'M');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'SCAFUUVRPH', N'Nelson ', N'S');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'SPXMIACFOH', N'Fort McMurray ', N'T');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'SSLFPMBQFA', N'Gatineau ', N'J');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'TH8LF9', N'Victoria', N'B');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'TISALRFXNC', N'Saint-Eustache ', N'U');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'TNCGRQUMHY', N'Brandon ', N'Y');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'URHLFISXEB', N'Hay River ', N'L');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'USCFVFDOSQ', N'Asbestos ', N'O');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'VHMFQKNDSF', N'Elliot Lake ', N'V');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'WGHTJUNIKO', N'Thunder Bay ', N'D');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'WGLWITWAOR', N'Lethbridge ', N'O');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'WTSVQNKDUJ', N'Temiskaming Shores ', N'X');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'XDCLMOVIXX', N'Happy Valley ', N'T');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'XXMMPGYJOP', N'Midland ', N'I');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'YBKAKVXHPN', N'Val-d ', N'D');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'YDYLDDNVRH', N'Stratford ', N'C');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'YGQRGYQHPQ', N'Hong Kong', N'S');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'YHMOMDAGIB', N'Belleville ', N'W');
INSERT INTO LocationPhysical (PhysicalLocationId, Label, SortValue) VALUES (N'YSCDNLBQAD', N'Campbell River ', N'N');