INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'01', N'Acme Seeds Inc.', N'10001');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'02', N'Acme Planting Ltd.', N'20006');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'03', N'Acme Harvesting Ltd.', N'30015');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'10', N'E.W. Scripps Company', N'40000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'11', N'Earthlink, Inc.', N'41000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'12', N'Eastman Chemical Company', N'42000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'13', N'Eastman Kodak Company', N'43000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'14', N'Eaton Corporation', N'44000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'15', N'Echostar Communications Corporation', N'45000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'16', N'Ecolab Inc.', N'46000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'17', N'Edison International', N'47000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'18', N'EGL Inc.', N'48000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'19', N'El Paso Corporation', N'49000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'20', N'Electronic Arts Inc.', N'50000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'21', N'Electronic Data Systems Corp.', N'51000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'22', N'Eli Lilly and Company', N'52000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'23', N'EMC Corporation', N'53000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'24', N'Emcor Group Inc.', N'54000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'25', N'Emerson Electric Co.', N'55000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'26', N'Encompass Services Corporation', N'56000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'27', N'Energizer Holdings Inc.', N'57000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'28', N'Energy East Corporation', N'58000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'29', N'Engelhard Corporation', N'59000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'30', N'Enron Corp.', N'60000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'31', N'Entergy Corporation', N'61000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'32', N'Enterprise Products Partners L.P.', N'62000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'33', N'EOG Resources, Inc.', N'63000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'34', N'Equifax Inc.', N'64000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'35', N'Equitable Resources Inc.', N'65000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'36', N'Equity Office Properties Trust', N'66000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'37', N'Equity Residential Properties Trust', N'67000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'38', N'Estee Lauder Companies Inc.', N'68000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'39', N'Exelon Corporation', N'69000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'40', N'Exide Technologies', N'70000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'41', N'Expeditors International of Washington Inc.', N'71000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'42', N'Express Scripts Inc.', N'72000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'43', N'ExxonMobil Corporation', N'73000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'44', N'Fairchild Semiconductor International Inc.', N'74000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'45', N'Family Dollar Stores Inc.', N'75000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'46', N'Farmland Industries Inc.', N'76000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'47', N'Federal Mogul Corp.', N'77000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'48', N'Federated Department Stores Inc.', N'78000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'49', N'Federal Express Corp.', N'79000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'50', N'Felcor Lodging Trust Inc.', N'80000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'51', N'Ferro Corp.', N'81000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'52', N'Fidelity National Financial Inc.', N'82000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'53', N'Fifth Third Bancorp', N'83000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'54', N'First American Financial Corp.', N'84000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'55', N'First Data Corp.', N'85000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'56', N'First National of Nebraska Inc.', N'86000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'57', N'First Tennessee National Corp.', N'87000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'58', N'FirstEnergy Corp.', N'88000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'59', N'Fiserv Inc.', N'89000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'60', N'Fisher Scientific International Inc.', N'90000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'61', N'FleetBoston Financial Co.', N'91000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'62', N'Fleetwood Enterprises Inc.', N'92000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'63', N'Fleming Companies Inc.', N'93000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'64', N'Flowers Foods Inc.', N'94000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'65', N'Flowserv Corp', N'95000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'66', N'Fluor Corp', N'96000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'67', N'FMC Corp', N'97000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'68', N'Foamex International Inc', N'98000');
INSERT INTO LocationCompany (CompanyCode, Label, ManagerWorkerNumber) VALUES (N'69', N'Foot Locker Inc', N'99000');